CREATE TABLE `data_platform_port_header_data`
(
  `Port`                             int(16) NOT NULL,
  `PortType`                         varchar(4) NOT NULL,
  `PortOwner`                        int(12) NOT NULL,
  `PortOwnerBusinessPartnerRole`     varchar(40) NOT NULL,
  `PrimaryLine`                      int(16) NOT NULL,
  `PersonResponsible`                varchar(40) DEFAULT NULL,
  `URL`                              varchar(200) DEFAULT NULL,
  `ValidityStartDate`                date NOT NULL,
  `ValidityEndDate`                  date NOT NULL,
  `DailyOperationStartTime           time NOT NULL,
  `DailyOperationEndTime`            time NOT NULL,
  `Description`                      varchar(60) NOT NULL,
  `LongText`                         varchar(1000) NOT NULL,
  `Introduction`                     varchar(200) DEFAULT NULL,
  `OperationRemarks`                 varchar(100) DEFAULT NULL,
  `PhoneNumber`                      varchar(40) DEFAULT NULL,
  `AvailabilityOfParking`            tinyint(1) DEFAULT NULL,
  `NumberOfParkingSpaces`            int(4) DEFAULT NULL,
  `Site`                             int(16) DEFAULT NULL,
  `SiteType`                         varchar(4) DEFAULT NULL,
  `Station`                          int(16) DEFAULT NULL,
  `Project`                          int(16) DEFAULT NULL,
  `WBSElement`                       int(8) DEFAULT NULL,
  `Tag1`                             varchar(40) DEFAULT NULL,
  `Tag2`                             varchar(40) DEFAULT NULL,
  `Tag3`                             varchar(40) DEFAULT NULL,
  `Tag4`                             varchar(40) DEFAULT NULL,
  `CreationDate`                     date NOT NULL,
  `CreationTime`                     time NOT NULL,
  `LastChangeDate`                   date NOT NULL,
  `LastChangeTime`                   time NOT NULL,
  `CreateUser`                       int(12) NOT NULL,
  `LastChangeUser`                   int(12) NOT NULL,
  `IsReleased`                       tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Port`),

    CONSTRAINT `DPFMPortHeaderDataPortType_fk` FOREIGN KEY (`PortType`) REFERENCES `data_platform_port_type_port_type_data` (`PortType`),
    CONSTRAINT `DPFMPortHeaderDataPortOwner_fk` FOREIGN KEY (`PortOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMPortHeaderDataPortOwnerBPRole_fk` FOREIGN KEY (`PortOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMPortHeaderDataPrimaryLine_fk` FOREIGN KEY (`PrimaryLine`) REFERENCES `data_platform_ferry_line_header_data` (`FerryLine`),
    CONSTRAINT `DPFMPortHeaderDataSite_fk` FOREIGN KEY (`Site`) REFERENCES `data_platform_site_header_data` (`Site`),
    CONSTRAINT `DPFMPortHeaderDataSiteType_fk` FOREIGN KEY (`SiteType`) REFERENCES `data_platform_site_type_site_type_data` (`SiteType`),
    CONSTRAINT `DPFMPortHeaderDataStation_fk` FOREIGN KEY (`Station`) REFERENCES `data_platform_station_header_data` (`Station`),
    CONSTRAINT `DPFMPortHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMPortHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMPortHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMPortHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
